### ISSUE TITLE
SDE ERROR: Could not find file:~/SDE/intel64/sde-pinplay-debugger.so

### ISSUE THREAD

**Issue by IamHuskar** [intel/pinplay-tools#5]
record --logfile=~/log/ls --  ls
when I use gdb_replay to replay a pinball file.
it shows "sde-pinplay-debugger.so" missing (it seems drdebug is no longer available?)
how to replay the recordfile with gdb?

**Comment by hgpatil** [comment]
% cd pinplay-tools/Examples
% ./install.drdebug.sh
will build and put sde-pinplay-debugger.so under SDE/ia32 and SDE/intel64
Update: https://github.com/intel/pinplay-tools/tree/main/DrDebug is the new GitHub home for DrDebug
% cd pinplay-tools/DrDebug
% ./install.drdebug.sh

**Comment by IamHuskar** [comment]
@hgpatil  btw . Will the gdb reverse-step  be supported in the future? like rr-debugger .

**Comment by hgpatil** [comment]
No such plans. Taking periodic checkpoints(pinballs) and going back to the last checkpoint and then going forward is one way to implement reverse-step if anyone wants to implement that.
Also, a new home for DrDebug is here: https://github.com/intel/pinplay-tools/tree/main/DrDebug (this is the new location of the 'install.drdebug.sh' script mentioned earlier).

**Comment by IamHuskar** [comment]
> No such plans. Taking periodic checkpoints(pinballs) and going back to the last checkpoint and then going forward is one way to implement reverse-step if anyone wants to implement that. Also, a new home for DrDebug is here: https://github.com/intel/pinplay-tools/tree/main/DrDebug (this is the new location of the 'install.drdebug.sh' script mentioned earlier).

thanks. and I have one last question. can pinplay support record/replay child process  (like execve or fork )?

**Comment by IamHuskar** [comment]
> > No such plans. Taking periodic checkpoints(pinballs) and going back to the last checkpoint and then going forward is one way to implement reverse-step if anyone wants to implement that. Also, a new home for DrDebug is here: https://github.com/intel/pinplay-tools/tree/main/DrDebug (this is the new location of the 'install.drdebug.sh' script mentioned earlier).
> 
> thanks. and I have one last question. can pinplay support record/replay child process (like execve or fork )?

solved:
I find the records  for child process in subdirectory. with fk prefix for fork .with ex prefix for execve.
pinplay it's a amazing project. thanks
